### ISSUE TITLE
Problem running new create-choo-app 

### ISSUE THREAD

**Issue by corderophi678** [choojs/create-choo-app#2]
Me: `npx create-choo-app my-choo-app && cd my-choo-app && npm start`

Getting an "Uncaught TypeError: Cannot read property 'DOMCONTENTLOADED' of undefined." When running a new create-choo-app. Console error references the indicated line below.

```javascript
...
[function(require, module, exports) {
        function serviceWorker(e, t) {
            return e = e || "/sw.js",
            t = t || {},
            assert.equal(typeof e, "string", "choo-service-worker: name should be type string"),
            assert.equal(typeof t, "object", "choo-service-worker: opts should be type object"),
            function(r, o) {
                assert.equal(typeof r, "object", "choo-service-worker: state should be type object"),
                assert.equal(typeof o, "object", "choo-service-worker: emitter should be type object"),
  /* Here --> */        o.on(r.events.DOMCONTENTLOADED, function() { 
                    t = mutate({
                        scope: "/"
                    }, t),
                    navigator.serviceWorker && navigator.onLine && navigator.serviceWorker.register(e, t).then(function(e) {
                        o.emit(events.INSTALLED, e)
                    }).catch(function(e) {
                        o.emit(events.ERROR, e)
                    })
                })
            }
        }
...
```

**Comment by yoshuawuyts** [comment]
Ah yeah, this is code for choo 6  - I'll make sure we install the preview then, awaiting the next major release ( next week or so I'm guessing)

**Comment by yoshuawuyts** [comment]
Fixed! (although now you'll get an error the sw.js can't be found)

**Comment by varjmes** [comment]
I'm still having this issue, meaning i can't progress with my app.

Fresh app using npx create-choo-app

edit: am on latest node, npm and npx.

edit: my error happens here in main.js though

```
  if (state.title !== TITLE) emit(state.events.DOMTITLECHANGE, TITLE)

```

it doesn't think `state.events exist`! :o

**Comment by yoshuawuyts** [comment]
Oh no! What's the version of Choo you have installed? V6 should have the events nicely attached to state https://github.com/choojs/choo/blob/master/index.js#L49

Are there perhaps any other errors in the console?

**Comment by varjmes** [comment]
@yoshuawuyts ah looks like npm was unhelpfully storing cached versions of Choo v5. I force updated everything and it's working now on v6. Thanks!

**Comment by yoshuawuyts** [comment]
Woot! 🎉
